spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tpo
    username: postgres
    password: 2002
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect


